---
- name: Download Tyk-Gateway Repository 
  get_url:
    url: "https://packagecloud.io/install/repositories/tyk/tyk-gateway/script.deb.sh"
    dest: /tmp/
    mode: 0755

- name: Add Tyk-Gateway Repository
  shell: "/tmp/script.deb.sh"

- name: Install Tyk-Gateway
  apt: 
    name: tyk-gateway 
    state: present 
    update_cache: yes

- name: Set config file
  template:
    src: config_file.j2
    dest: "{{ tyk_path }}/tyk.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
      - Start Tyk-Gateway

- name: Delete API config folder
  file: 
    path: "{{ tyk_api_configs_path }}/" 
    state: absent

- name: Create API config folder
  file:
    dest: "{{ tyk_api_configs_path }}"
    owner: "root"
    group: "root"
    mode: 0755
    state: directory

- name: Create Files Config Files
  template:
    src: keyless_config_base.j2
    dest: "{{ tyk_api_configs_path }}/{{ item }}.json"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ config_file | list }}"
  notify:
      - Restart Tyk-Gateway
